src/CaroGFaimBundle/Entity/plat.php
<?php

namespace CaroGFaimBundle\Entity;


use CaroGFaimBundle\Entity\type_plat;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * plat
 *
 * @UniqueEntity(fields="libelle", message="Ce plat existe déjà.")
 */
class plat
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $libelle;

    /**
     * @var int
     */
    private $note;

    /**
     * @var string
     */
    private $annotations;

    /**
     * @var string
     * @Assert\File(maxSize="1500k", mimeTypes = {"image/jpeg", "image/png"},
     *     mimeTypesMessage = "Veuillez sélectionner une photo au format JPEG ou PNG")
     */
    private $photofilename;

    /**
     * @var CaroGFaimBundle\Entity\type_plat
     */
    private $type_plat;

    /**
     * @var ArrayCollection
     */
    private $ingredients;

    /**
     * @var CaroGFaimBundle\Entity\diner
     */
    private $diner;

    /**
     * constructor
     */
    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->note = "0";
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set libelle
     *
     * @param string $libelle
     * @return plat
     */
    public function setLibelle($libelle)
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Get libelle
     *
     * @return string
     */
    public function getLibelle()
    {
        return $this->libelle;
    }

    /**
     * Set note
     *
     * @param integer $note
     * @return plat
     */
    public function setNote($note)
    {
        $this->note = $note;

        return $this;
    }

    /**
     * Get note
     *
     * @return integer
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Set annotations
     *
     * @param string $annotations
     * @return plat
     */
    public function setAnnotations($annotations)
    {
        $this->annotations = $annotations;

        return $this;
    }

    /**
     * Get annotations
     *
     * @return string
     */
    public function getAnnotations()
    {
        return $this->annotations;
    }

    /**
     * Set photo filename
     *
     * @param string $filename
     * @return plat
     */
    public function setPhotofilename($filename)
    {
        $this->photofilename = $filename;

        return $this;
    }

    /**
     * Get photo filename
     *
     * @return string
     */
    public function getPhotofilename()
    {
        return $this->photofilename;
    }

    /*
     * @var string
     */
    private $path;

    public function getAbsolutePath()
    {
        return null === $this->photofilename
            ? null
            : $this->getUploadRootDir().'/'.$this->photofilename;
    }

    public function getWebPath()
    {
        return empty($this->photofilename)
            ? null
            : $this->getUploadDir().'/'.$this->photofilename;
    }

    public function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../web/'.$this->getUploadDir();
    }

    public function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'bundles/carogfaim/upload';
    }

    /**
     * Set type_plat
     *
     * @param \CaroGFaimBundle\Entity\type_plat $typePlat
     * @return plat
     */
    public function setTypePlat(\CaroGFaimBundle\Entity\type_plat $typePlat)
    {
        $this->type_plat = $typePlat;

        return $this;
    }

    /**
     * Get type_plat
     *
     * @return \CaroGFaimBundle\Entity\type_plat
     */
    public function getTypePlat()
    {
        return $this->type_plat;
    }

    /**
     * Add ingredients
     *
     * @param \CaroGFaimBundle\Entity\ingredient $ingredients
     * @return plat
     */
    public function addIngredient(\CaroGFaimBundle\Entity\ingredient $ingredients)
    {
        $this->ingredients[] = $ingredients;

        return $this;
    }

    /**
     * Remove ingredients
     *
     * @param \CaroGFaimBundle\Entity\ingredient $ingredients
     */
    public function removeIngredient(\CaroGFaimBundle\Entity\ingredient $ingredients)
    {
        $this->ingredients->removeElement($ingredients);
    }

    /**
     * Get ingredients
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getIngredients()
    {
        return $this->ingredients;
    }

    /**
     * Set diner
     *
     * @param \CaroGFaimBundle\Entity\diner $diner
     * @return plat
     */
    public function setDiner(\CaroGFaimBundle\Entity\diner $diner = null)
    {
        $this->diner = $diner;

        return $this;
    }

    /**
     * Get diner
     *
     * @return \CaroGFaimBundle\Entity\diner
     */
    public function getDiner()
    {
        return $this->diner;
    }
}

src/CaroGFaimBundle/Form/platType.php
<?php

namespace CaroGFaimBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class platType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle', null, array('label'=>'Nom du plat : '))
            ->add('type_plat', null, array('label'=>'Type : '))
            ->add('ingredients', null, array('label'=>'Ingrédients : '))
           // ->add('note', null, array('label'=>'Attribuer une note :', 'attr' => array('min'=>'0', 'max'=>'5')))
            ->add('annotations', null, array('required' => false, 'data'=>'', 'label'=> 'Annotations : '))
            ->add('photofilename', FileType::class, array('required' => false, 'data'=>'', 'label'=> 'Joindre une photo : '))
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CaroGFaimBundle\Entity\plat'
        ));
    }
}

src/CaroGFaimBundle/Controller/platController.php
<?php

namespace CaroGFaimBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use CaroGFaimBundle\Entity\plat;
use CaroGFaimBundle\Form\platType;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Response;

/**
 * plat controller.
 *
 */
class platController extends Controller
{
    /**
     * @var string
     */
    private $oldPhoto;

    /**
     * Lists all plat entities.
     *
     */
    public function indexAction()
    {
        $form = $this->createFormBuilder()
            ->setMethod('POST')
            ->getForm();

        $em = $this->getDoctrine()->getManager();

        $type_plats = $em->getRepository('CaroGFaimBundle:plat')->findAllPlatsByType();

        return $this->render('CaroGFaimBundle:plat:index.html.twig', array(
            'type_plats' => $type_plats,
            'form' => $form->createView()
        ));
    }

    /**
     * Creates a new plat entity.
     *
     */
    public function newAction(Request $request)
    {
        $plat = new plat();
        $form = $this->createForm('CaroGFaimBundle\Form\platType', $plat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->updateUploadedFile($form, $plat)) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($plat);
                $em->flush();
            }

            return $this->redirectToRoute('plat_show', array('id' => $plat->getId()));
        }

        return $this->render('CaroGFaimBundle:plat:new.html.twig', array(
            'plat' => $plat,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a plat entity.
     *
     */
    public function showAction(plat $plat)
    {
        $deleteForm = $this->createDeleteForm($plat);

        return $this->render('CaroGFaimBundle:plat:show.html.twig', array(
            'plat' => $plat,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing plat entity.
     *
     */
    public function editAction(Request $request, plat $plat)
    {
        $deleteForm = $this->createDeleteForm($plat);

        $this->oldPhoto = $plat->getPhotofilename();

        $editForm = $this->createForm('CaroGFaimBundle\Form\platType', $plat);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            if ($this->updateUploadedFile($editForm, $plat)) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($plat);
                $em->flush();
            }
            return $this->redirectToRoute('plat_show', array('id' => $plat->getId()));
        }

        return $this->render('CaroGFaimBundle:plat:edit.html.twig', array(
            'plat' => $plat,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }
    /**
     * Displays a form to edit an existing plat entity.
     *
     */
    public function voteAction(Request $request, plat $plat)
    {
        $em = $this->getDoctrine()->getManager();
        $str = $request->getContent();
        $array_vote = explode("=", $str);
        $plat->setNote($array_vote[1]);
        $em->persist($plat);
        $em->flush();
        return new Response("");
    }

    /**
     * Deletes a plat entity.
     *
     */
    public function deleteAction(Request $request, plat $plat)
    {
        $form = $this->createDeleteForm($plat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($plat);
            $em->flush();
        }

        return $this->redirectToRoute('plat_index');
    }

    /**
     * Creates a form to delete a plat entity.
     *
     * @param plat $plat The plat entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(plat $plat)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('plat_delete', array('id' => $plat->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }

    /**
     * Save on disk the uploaded file
     *
     * @param \Symfony\Component\Form\Form The form
     * @param \CaroGFaimBundle\Entity\plat
     *
     * @return bool true if no error
     */
    private function updateUploadedFile(\Symfony\Component\Form\Form $form, plat $plat)
    {
        // the file property can be empty if the field is not required

        $file = ($form['photofilename']->getData());

        if (!is_object($file)) {
            $plat->setPhotofilename($this->oldPhoto);
            return true;
        }


        $extension = $file->guessExtension();
        if (!$extension) {
            // extension cannot be guessed
            $extension = 'bin';
        }
        $newFilename = sha1(uniqid(mt_rand(), true)).'.'.$extension;
        $file->move($plat->getUploadRootDir(), $newFilename);

        $plat->setPhotofilename($newFilename);


        return true;
    }

}

src/CaroGFaimBundle/Resources/views/plat/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Modifier :<br>{{ plat.libelle }}</h1>

    <div class="center">
        {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <div class="photo_edit" style="background-image:url('{{ asset(plat.webPath) }}');"></div>
        <input type="submit" value="Enregistrer" />
        <input type="button" value="Annuler" back_href="{{ path('plat_index') }}" />
        {{ form_end(edit_form) }}
    </div>

{% endblock %}

src/CaroGFaimBundle/Resources/views/plat/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Mes plats</h1>

    <form method="get" action="{{ path('plat_new') }}">
        <button class="marg" type="submit">Nouveau plat</button>
    </form>

    {{ form_start(form, {'class': 'form_list' }) }}
    <input type="hidden" name="_method" value="GET" >

    <div class="column-list-ingred">
        {% for type_plat in type_plats %}
            {% if type_plat.plats.count %}
            <table class="table table-bordered td-two">
                <thead>
                    <tr>
                        <th colspan="3">{{ type_plat.libelle }}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for plat in type_plat.plats %}
                    <tr>
                        <td>
                            {% if plat.webPath %}
                                <div class="photo" style="background-image:url('{{ asset(plat.webPath) }}');"></div>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ path('plat_show', { 'id': plat.id }) }}">{{ plat.libelle }}</a>
                            <div class="row lead align_stars">
                                <div id="stars-existing" class="starrr" id_plat="{{ plat.id }}" vote="{{ plat.note }}"></div>
                            </div>
                        </td>
                        <td>
                            <button type="submit" class="modif" formaction="{{ path('plat_edit', { 'id': plat.id }) }}"> modif. </button>

                            {% if plat.diner %}
                                <button class="button-no-click" disabled="disabled"> suppr. </button>
                            {% else %}
                                <button type="submit" class="delete" formaction="{{ path('plat_delete', { 'id': plat.id }) }}"> suppr. </button>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            {% endif %}
        {% endfor %}
    </div>

    {{ form_end(form) }}

{% endblock %}

{% block javascripts %}
	{{ parent() }}
        <script src="{{ asset('bundles/carogfaim/js/script.js') }}"></script>
{% endblock %}

src/CaroGFaimBundle/Resources/views/plat/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Nouveau plat</h1>

    <div class="center">
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="Ajouter" />
    <input type="button" value="Annuler" back_href="{{ path('plat_index') }}" />
    {{ form_end(form) }}
    </div>

{% endblock %}

src/CaroGFaimBundle/Resources/views/plat/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>{{ plat.libelle }}</h1>

    <div class="photo_show" style="background-image:url('{{ asset(plat.webPath) }}');"></div>

    <div class="show-table">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Type de plat</th>
            <th>Note</th>
            <th>Ingrédients</th>

        </tr>
        </thead>

        <tbody>
            <tr>
                <td>{{ plat.typeplat }}</td>
                <td>{{ plat.note }}</td>
                <td>
                    {% if plat.ingredients.count %}
                        <ul>
                        {% for ingredient in plat.ingredients %}
                            <li>{{ ingredient.libelle }}</li>
                        {% endfor %}
                        </ul>
                    {% else %}
                        Aucun ingrédient.
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Annotations : </th>
                <td colspan="2" style="text-align: left">{{ plat.annotations }}</td>
            </tr>
            <tr>
                <td colspan="2">
                    <form method="get" action="{{ path('plat_index') }}">
                        <button class="marg" type="submit">Retour à la liste</button>
                    </form>
                </td>
                <td>
                    <form method="get" action="{{ path('plat_edit', { 'id': plat.id }) }}">
                        <button type="submit"> modif. </button>
                    </form>
                    {#
                    {% if plat.diners.count %}
                        <button class="button-no-click" disabled="disabled"> suppr. </button>
                    {% else %}
                    #}
                    {{ form_start(delete_form, {'action': path('plat_delete', { 'id': plat.id }) }) }}
                    <button type="submit"> suppr. </button>
                    {{ form_end(delete_form) }}
                    {#
                    {% endif %}
                    #}
                </td>

            </tr>
        </tbody>
    </table>

{% endblock %}