src/CaroGFaimBundle/Entity/ingredient.php
<?php

namespace CaroGFaimBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ingredient
 *
 * @UniqueEntity(fields="libelle", message="Cet ingrédient existe déjà.")
 */
class ingredient
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $libelle;

    /**
     * @var \CaroGFaimBundle\Entity\categorie
     */
    private $categorie;

    /**
     * @var ArrayCollection
     */
    private $personnes;

    /**
     * @var ArrayCollection
     */
    private $apparaitre_plats;

    /**
     * constructor
     */
    public function __construct()
    {
        $this->personnes = new ArrayCollection();
        $this->apparaitre_plats = new ArrayCollection();
    }

    /**
     * get libelle
     *
     * @return string
     */
    public function __toString()
    {
        return $this->libelle;
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set libelle
     *
     * @param string $libelle
     * @return ingredient
     */
    public function setLibelle($libelle)
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Get libelle
     *
     * @return string
     */
    public function getLibelle()
    {
        return $this->libelle;
    }


    /**
     * Set categorie
     *
     * @param \CaroGFaimBundle\Entity\categorie $categorie
     * @return ingredient
     */
    public function setCategorie(\CaroGFaimBundle\Entity\categorie $categorie = null)
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * Get categorie
     *
     * @return \CaroGFaimBundle\Entity\categorie
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

    /**
     * Add personnes
     *
     * @param \CaroGFaimBundle\Entity\personne $personnes
     * @return ingredient
     */
    public function addPersonne(\CaroGFaimBundle\Entity\personne $personnes)
    {
        $this->personnes[] = $personnes;

        return $this;
    }

    /**
     * Remove personnes
     *
     * @param \CaroGFaimBundle\Entity\personne $personnes
     */
    public function removePersonne(\CaroGFaimBundle\Entity\personne $personnes)
    {
        $this->personnes->removeElement($personnes);
    }

    /**
     * Get personnes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPersonnes()
    {
        return $this->personnes;
    }

    /**
     * Add plats
     *
     * @param \CaroGFaimBundle\Entity\plat $plats
     * @return ingredient
     */
    public function addApparaitrePlat(\CaroGFaimBundle\Entity\plat $plats)
    {
        $this->apparaitre_plats[] = $plats;

        return $this;
    }

    /**
     * Remove plats
     *
     * @param \CaroGFaimBundle\Entity\plat $plats
     */
    public function removeApparaitrePlat(\CaroGFaimBundle\Entity\plat $plats)
    {
        $this->apparaitre_plats->removeElement($plats);
    }

    /**
     * Get plats
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getApparaitrePlats()
    {
        return $this->apparaitre_plats;
    }
}

src/CaroGFaimBundle/Form/ingredientType.php
<?php

namespace CaroGFaimBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ingredientType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle', null, array('label'=>'Libellé : '))
            ->add('categorie', null, array('label'=>"Catégorie :"))
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CaroGFaimBundle\Entity\ingredient'
        ));
    }
}

src/CaroGFaimBundle/Controller/ingredientController.php
<?php

namespace CaroGFaimBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use CaroGFaimBundle\Entity\ingredient;
use CaroGFaimBundle\Form\ingredientType;

/**
 * ingredient controller.
 *
 */
class ingredientController extends Controller
{
    /**
     * Lists all ingredient entities.
     *
     */
    public function indexAction()
    {
        $form = $this->createFormBuilder()
            ->setMethod('POST')
            ->getForm();

        $em = $this->getDoctrine()->getManager();

        $categories = $em->getRepository('CaroGFaimBundle:ingredient')->findAllIngredientsByCategories();

        return $this->render("CaroGFaimBundle:ingredient:index.html.twig", array(
            'categories' => $categories,
            'form' => $form->createView()
        ));
    }

    /**
     * Creates a new ingredient entity.
     *
     */
    public function newAction(Request $request)
    {
        $ingredient = new ingredient();
        $form = $this->createForm('CaroGFaimBundle\Form\ingredientType', $ingredient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($ingredient);
            $em->flush();

            return $this->redirectToRoute('ingredient_index');
        }

        return $this->render("CaroGFaimBundle:ingredient:new.html.twig", array(
            'ingredient' => $ingredient,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a ingredient entity.
     *
     */
    public function showAction(ingredient $ingredient)
    {
        $deleteForm = $this->createDeleteForm($ingredient);

        return $this->render("CaroGFaimBundle:ingredient:show.html.twig", array(
            'ingredient' => $ingredient,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing ingredient entity.
     *
     */
    public function editAction(Request $request, ingredient $ingredient)
    {
        $deleteForm = $this->createDeleteForm($ingredient);
        $editForm = $this->createForm('CaroGFaimBundle\Form\ingredientType', $ingredient);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($ingredient);
            $em->flush();

            return $this->redirectToRoute('ingredient_index');
        }

        return $this->render("CaroGFaimBundle:ingredient:edit.html.twig", array(
            'ingredient' => $ingredient,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a ingredient entity.
     *
     */
    public function deleteAction(Request $request, ingredient $ingredient)
    {
        $form = $this->createDeleteForm($ingredient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($ingredient);
            $em->flush();
        }

        return $this->redirectToRoute('ingredient_index');
    }

    /**
     * Creates a form to delete a ingredient entity.
     *
     * @param ingredient $ingredient The ingredient entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(ingredient $ingredient)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('ingredient_delete', array('id' => $ingredient->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/CaroGFaimBundle/Resources/views/ingredient/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Modifier :<br>{{ ingredient.libelle }}</h1>

    <div class="center">
        {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Enregistrer" />
        <input type="button" value="Annuler" back_href="{{ path('ingredient_index') }}" />
        {{ form_end(edit_form) }}
    </div>

{% endblock %}

src/CaroGFaimBundle/Resources/views/ingredient/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Mes ingrédients</h1>

    <form method="get" action="{{ path('ingredient_new') }}">
        <button class="marg" type="submit">Nouvel ingrédient</button>
    </form>

    {{ form_start(form, {'class': 'form_list' }) }}
    <input type="hidden" name="_method" value="GET" >

    <div class="column-list-ingred">

        {% for categorie in categories %}
            {% if categorie.ingredients.count %}

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th colspan="2">{{ categorie.libelle }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ingredient in categorie.ingredients %}

                        <tr>
                            <td>
                                {{ ingredient.libelle }}
                            </td>
                            <td>
                                    <button type="submit" class="modif" formaction="{{ path('ingredient_edit', { 'id': ingredient.id }) }}"> modif. </button>


                                {% if ingredient.apparaitrePlats.count %}
                                    <button class="button-no-click" disabled="disabled"> suppr. </button>
                                {% else %}

                                    <button type="submit" class="delete" formaction="{{ path('ingredient_delete', { 'id': ingredient.id }) }}"> suppr. </button>

                                {% endif %}

                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        {% endfor %}
    </div>

    {{ form_end(form) }}

{% endblock %}

src/CaroGFaimBundle/Resources/views/ingredient/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Nouvel ingrédient</h1>

    <div class="center">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Ajouter" />
        <input type="button" value="Annuler" back_href="{{ path('ingredient_index') }}" />
        {{ form_end(form) }}
    </div>

{% endblock %}

src/CaroGFaimBundle/Resources/views/ingredient/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>ingredient</h1>
    <form method="get" action="{{ path('ingredient_new') }}">
        <button class="marg" type="submit">Nouvel ingrédient</button>
    </form>
    <form method="get" action="{{ path('ingredient_index') }}">
        <button class="marg" type="submit">Retour à la liste</button>
    </form>

    <ul>
        <li>
            <a href="{{ path('ingredient_index') }}">Retour</a>
        </li>
    </ul>
    <table>
        <tbody>
            <tr>
                <th>Libellé&#8239;:&nbsp;</th>
                <td>{{ ingredient.libelle }}</td>
            </tr>
            <tr>
                <th>Catégorie&#8239;:&nbsp;</th>
                <td>{{ ingredient.categorie }}</td>
            </tr>
        </tbody>
    </table>

{% endblock %}